"""
Database package for ANPRX Edge ANPR and Trip Management.
"""
from db.config import get_database_url
from db.session import engine, SessionLocal, get_db, init_db
from db.models import (
    Base,
    Role,
    User,
    Transporter,
    Vehicle,
    VehiclePlate,
    Driver,
    Gate,
    Camera,
    ModelVersion,
    ScheduledTrip,
    TripStatusHistory,
    VehicleDetection,
    PlatePrediction,
    PlatePredictionFrame,
    EntryExitEvent,
    GateDecision,
    WhitelistEntry,
    WatchlistEntry,
    Alert,
    AlertDelivery,
    AuditLog,
    ManualCorrection,
    CameraHealth,
    DailyGateSummary,
)

__all__ = [
    "get_database_url",
    "engine",
    "SessionLocal",
    "get_db",
    "init_db",
    "Base",
    "Role",
    "User",
    "Transporter",
    "Vehicle",
    "VehiclePlate",
    "Driver",
    "Gate",
    "Camera",
    "ModelVersion",
    "ScheduledTrip",
    "TripStatusHistory",
    "VehicleDetection",
    "PlatePrediction",
    "PlatePredictionFrame",
    "EntryExitEvent",
    "GateDecision",
    "WhitelistEntry",
    "WatchlistEntry",
    "Alert",
    "AlertDelivery",
    "AuditLog",
    "ManualCorrection",
    "CameraHealth",
    "DailyGateSummary",
]
